tours = {
  1: {
    "title": "Гірські бунгало на Пазуркі",
    "description": "Стильний котедж з захоплюючим видом на озеро Чарштин, поруч із велосипедною доріжкою Velo Czorsztyn!",
    "picture": "https://a0.muscache.com/im/pictures/bc1170d7-d0f6-4185-a5c8-1eea5eda30cb.jpg?im_w=1200",
    "price": "6581 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "3 березня",
  },
  2: {
    "title": "Котедж на озері",
    "description": "Коттедж Nateria Lake Svätno - це чарівне місце в 10 хвилинах від Ольшина.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-589099197559108828/original/49fa1da9-054c-46cb-ade5-7d1914956f9d.jpeg?im_w=1200",
    "price": "10309 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "1 березня",
  },
  3: {
    "title": "Будинок на озері Вадзьог",
    "description": "Запрошуємо вас до комфортабельної цілодобової дачі, розташованої на озері Вадзьог, в закритому поселенні в Шипрі.",
    "picture": "https://a0.muscache.com/im/pictures/e81f6ec5-bc2a-46e7-b056-745a50efabb9.jpg?im_w=960",
    "price": "2853 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "3 березня",
  },
  4: {
    "title": "Stylchyn Park",
    "description": "Запрошуємо вас до нашої чарівної квартири, де ви зануритеся в унікальний шарм гірського ландшафту.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-1050596039125545708/original/dd4a616d-fdf1-4d22-b100-60b18de1c1b5.jpeg?im_w=960",
    "price": "5173 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "1 березня",
  },
  5: {
    "title": "Березовий схил",
    "description": "Шукаєте місце, де можна провести час подалі від міської метушні? Запрошуємо вас орендувати новий затишний дерев 'яний будинок на 6 осіб у лісі.",
    "picture": "https://a0.muscache.com/im/pictures/2ca81d18-d548-4691-9ec4-55f1cc1e1b01.jpg?im_w=960",
    "price": "5249 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "3 березня",
  },
  6: {
    "title": "Kalwa Lake House - Lake",
    "description": "Сучасний і розкішний будинок.Вона розташована в мальовничій зоні на півострові Острув у Пасеймії.",
    "picture": "https://a0.muscache.com/im/pictures/c0c28273-3b73-4584-a44f-86b36dcd66bc.jpg?im_w=960",
    "price": "8597 ніч",
    "stars": "4.5",
    "country": "Польща",
    "nights": "5",
    "date": "3 березня",
  },
  7: {
    "title": "Stylchyn Park",
    "description": "Запрошуємо вас до нашої чарівної квартири, розташованої на вулиці Za Stylchyn, де ви зануритеся в унікальний шарм гірського ландшафту. ",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-1065845943096789693/original/d900367e-014c-4653-93aa-29318dd5d87e.jpeg?im_w=960",
    "price": "4450 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "3 березня",
  },
  8: {
    "title": "Лавка та Сілавка",
    "description": "Будинок з видом на озеро, цілорічна гідромасажна ванна на відкритому повітрі, сауна на відкритому повітрі та приватний причал. Спокій, затишок, відпочинок, відпочинок.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-750577467611266122/original/c5c234bb-8a94-4b91-aa24-3f40297f6da5.jpeg?im_w=960",
    "price": "17194 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "3 березня",
  },
  9: {
    "title": "Под Агламі на озері Таджті",
    "description": "Цілорічний будинок розташований на озері Таджта у Вілкасі-Залесі, за 4 кілометри від Гіжицько.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-52403796/original/1e1430d7-d42c-404d-9669-b07dff1efc76.jpeg?im_w=480",
    "price": "4679 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "1 березна",
  },
  10: {
    "title": "За Лісом Біля Води",
    "description": "Ласкаво просимо до нашого унікального 100-річного будинку, що стоїть на найчистішому озері в Вармії-Мазурії.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-923078225085296527/original/f98ceb61-51ba-46f2-a2da-a3b7097a1e02.jpeg?im_w=960",
    "price": "11450 ніч",
    "stars": "3.5",
    "country": "Польща",
    "nights": "5",
    "date": "3 березня",
  },
  11: {
    "title": "Парк Стилчин",
    "description": "Запрошуємо вас до нашої чарівної квартири, де ви зануритеся в унікальний шарм гірського ландшафту. ",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-1087002577915105509/original/1f1ef7da-ed21-4ba4-aa48-e3263d8637cf.jpeg?im_w=960",
    "price": "4450 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "3 березня",
  },
  12: {
    "title": "Просторий будинок",
    "description": "Розслабтеся в нашому приголомшливому будинку, якому понад 100 років.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-622398886246546271/original/c88f55ff-d7e9-4c54-b027-b0f2d1cbfe92.png?im_w=960",
    "price": "3233 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "4 березня",
  },
  13: {
    "title": "Котедж у озерному парку",
    "description": "Ласкаво просимо до одного з кількох комфортабельних будинків з підігрівом.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-21941813/original/140e5a27-3cca-4342-bbc2-dac06f218f3b.jpeg?im_w=960",
    "price": "5744 ніч",
    "stars": "5",
    "country": "Польща",
    "nights": "5",
    "date": "1 квітня",
  },
  14: {
    "title": "Vila Сари",
    "description": "Вілла розташована в тихому житловому районі, де можна насолодитися красою захоплюючого виду на віллу приблизно в 25 хвилинах від Бухареста.",
    "picture": "https://a0.muscache.com/im/pictures/8dc01d54-3c33-41f0-97ce-c5232402164b.jpg?im_w=960",
    "price": "8977 ніч",
    "stars": "5",
    "country": "Румунія",
    "nights": "5",
    "date": "1 березня",
  },
  15: {
    "title": "Віла Насолоджуйтеся",
    "description": "Відпочиньте всією сім 'єю в цьому затишному місці для розміщення. ",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-683912423786096329/original/3b52ce34-20e8-4660-b551-62c281e11a2b.jpeg?im_w=960",
    "price": "5401 ніч",
    "stars": "4",
    "country": "Румунія",
    "nights": "5",
    "date": "1 березня",
  },
  16: {
    "title": "Шале верби",
    "description": "Шале WILLOW 's, розташоване на березі озера СОМОВА, є місцем відпочинку та позбавлення від повсякденного стресу.",
    "picture": "https://a0.muscache.com/im/pictures/13ad4874-67bd-46ed-8782-ddf1c7490412.jpg?im_w=960",
    "price": "2396 ніч",
    "stars": "5",
    "country": "Румунія",
    "nights": "5",
    "date": "8 листопада",
  },
  17: {
    "title": "Belvedere Snagov 2",
    "description": "Приходьте і відпочиньте в спокійному, затишному та стильному помешканні з сім 'єю, друзями або подругою, за межами міської метушні. ",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-876402145206629962/original/00677ef8-a60c-4753-adac-27b2520716ef.jpeg?im_w=960",
    "price": "4108 ніч",
    "stars": "5",
    "country": "Румунія",
    "nights": "5",
    "date": "1 березня",
  },
  18: {
    "title": "Vila Montana",
    "description": "Вілла Montana Văliug розташована в 5 хвилинах ходьби від Ponton Casa Baraj",
    "picture": "https://a0.muscache.com/im/pictures/a4dae035-b945-43e8-97d6-d79d7b05c10b.jpg?im_w=960",
    "price": "13276 ніч",
    "stars": "5",
    "country": "Румунія",
    "nights": "5",
    "date": " 3 березня",
  },
  19: {
    "title": "Дзен Хаус",
    "description": "Дружній дім підходить для сімей або групи друзів, недалеко від гори Чахлау, Биказу, озера Ізвору Мунтелуй та кількох монастирів",
    "picture": "https://a0.muscache.com/im/pictures/e68c1530-5949-4438-acbf-c94c76d212bc.jpg?im_w=960",
    "price": "1864 ніч",
    "stars": "5",
    "country": "Румунія",
    "nights": "5",
    "date": "9 червня",
  },
  20: {
    "title": "Вілла Aqualina",
    "description": "Озеро , гори, ліс , повітря та спокій роблять віллу Aqualina прекрасним місцем, яке тримає вас в тиші!",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-720133901631573560/original/1a0e2769-a73a-4901-9644-ec96ece892cd.jpeg?im_w=960",
    "price": "12781 ніч",
    "stars": "5",
    "country": "Румунія",
    "nights": "5",
    "date": "3 березня",
  },
  21: {
    "title": "«La Mamuca»",
    "description": "Я ношу цю назву як ціну і люблю . Я був побудований сім десятиліть тому чудовим чоловіком, а потім залишив свою спадщину, я був змінений для туристичних цілей!",
    "picture": "https://a0.muscache.com/im/pictures/00cc6efe-8da3-4b3e-a64b-58d97bee8bd4.jpg?im_w=960",
    "price": "10347 ніч",
    "stars": "5",
    "country": "Румунія",
    "nights": "5",
    "date": "1 березня",
  },
  22: {
    "title": "Дивовижна 6BR",
    "description": "Ця вілла інкапсулює все, що чудово про Убуд в межах одного місця, її надзвичайно великий і просторий дизайн домінує вертикальність його загальної структури.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-53983980/original/616c1c73-e91b-496f-8ffc-66cf6e32e045.jpeg?im_w=960",
    "price": "16129 ніч",
    "stars": "5",
    "country": "Індонезія",
    "nights": "5",
    "date": "19 квітня",
  },
  23: {
    "title": "Вілла на Улувату",
    "description": "Вілла Terracotta - це видатна розкішна вілла, що наглядає за Індійським океаном, Кутою, Семіньяком і Південним Балі.",
    "picture": "https://a0.muscache.com/im/pictures/7a216ca0-4d00-4870-b8f3-c5fdbb833985.jpg?im_w=960",
    "price": "12553 ніч",
    "stars": "5",
    "country": "Індонезія",
    "nights": "5",
    "date": "6 березня",
  },
  24: {
    "title": "Квартира недалеко від центру",
    "description": "Ідеально підходить для приміських/парних поїздок Коротка поїздка як дуже хороше сполучення автобус/поїзд",
    "picture": "https://a0.muscache.com/im/pictures/cc52e51b-540f-4008-93af-a1907cacc98f.jpg?im_w=960",
    "price": "44964 місяць",
    "stars": "5",
    "country": "Німеччина",
    "nights": "30",
    "date": "1 березня",
  },
  25: {
    "title": "Квартира Copacabana",
    "description": "Квартира площею приблизно 25 м² з міні-кухнею пропонує все необхідне.",
    "picture": "https://a0.muscache.com/im/pictures/ee9b78df-9c1a-463c-913c-4807eadbcfa8.jpg?im_w=960",
    "price": "115758 місяць",
    "stars": "5",
    "country": "Німеччина",
    "nights": "30",
    "date": "1 березня",
  },
  26: {
    "title": "Сучасна студія з балконом",
    "description": "Студія розташована в Munico, сучасній будівлі в затишному районі Obergiesing.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-41711024/original/7f26c83d-75c0-4678-9895-78f3390149cb.png?im_w=960",
    "price": "115758 місяць",
    "stars": "5",
    "country": "Німеччина",
    "nights": "30",
    "date": "3 березня",
  },
  27: {
    "title": "Студія Locke",
    "description": "Ласкаво просимо на нову базу в стилі середини століття в баварській столиці, що знаходиться в декількох хвилинах від місця проведення Октоберфесту.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-48038492/original/adb7abc8-f27c-4f91-8e55-384fdabba659.jpeg?im_w=960",
    "price": "45862 місяць",
    "stars": "5",
    "country": "Німеччина",
    "nights": "30",
    "date": "1 березня",
  },
  28: {
    "title": "«Zur Sommerfeld»",
    "description": "Наша квартира для відпочинку розташована в Сосі, всього в 8 км (11 хвилин) від Ейбенстока та купальних садів.",
    "picture": "https://a0.muscache.com/im/pictures/a6fad89e-d1c9-434d-96d2-0bf1404d42e9.jpg?im_w=960",
    "price": "69614 місяць",
    "stars": "5",
    "country": "Німеччина",
    "nights": "30",
    "date": "1 березня",
  },
  29: {
    "title": "Сучасна квартира поблизу пляжу",
    "description": "Нарешті, у настрій для тихого, розслабленого відпочинку біля моря (Балтійського моря)!",
    "picture": "https://a0.muscache.com/im/pictures/5186c64f-b3fb-4597-b0d5-6ebccfa71ffe.jpg?im_w=960",
    "price": "96852 місяць",
    "stars": "5",
    "country": "Німеччина",
    "nights": "30",
    "date": "1 березня",
  },
  30: {
    "title": "Студія City Studio",
    "description": "Ласкаво просимо до нової бази, створеної в середині століття, у столиці Баварії, за кілька хвилин від місця проведення Октоберфесту.",
    "picture": "https://a0.muscache.com/im/pictures/miso/Hosting-48038769/original/4db5aecb-0d67-4b30-a23e-9e697db6ad95.jpeg?im_w=960",
    "price": "96852 місяць",
    "stars": "5",
    "country": "Німеччина",
    "nights": "30",
    "date": "1 березня",
  },
  31: {
    "title": "Яскравий T2",
    "description": "Прийдіть і підзарядьте батареї в цій яскравій і тихій квартирі площею 50 м².",
    "picture": "https://a0.muscache.com/im/pictures/72439a3c-f93c-45f2-ab53-d1eb61ec5d98.jpg?im_w=960",
    "price": "47398 місяць",
    "stars": "5",
    "country": "Франція",
    "nights": "30",
    "date": "1 березня",
  },
  32: {
    "title": "Студійна кімната",
    "description": "Студійна кімната (ліжко 130) на 3-му поверсі з ліфтом безпечного помешкання (значок), тиха та добре утримується з  басейном (відкрита з 1,06 до 30.09), садом і майданчиком для петанк. ",
    "picture": "https://a0.muscache.com/im/pictures/8c806c13-13ab-44c4-a737-00cf65fd1066.jpg?im_w=960",
    "price": "52572 місяць",
    "stars": "5",
    "country": "Франція",
    "nights": "30",
    "date": "1 березня",
  },
  33: {
    "title": "Студійний Герцогство",
    "description": "Невелика студія в задній частині двору. Тихо.",
    "picture": "https://a0.muscache.com/im/pictures/19558bd3-7c9f-4882-9934-04efb93e0f85.jpg?im_w=960",
    "price": "49757 місяць",
    "stars": "5",
    "country": "Франція",
    "nights": "30",
    "date": "1 березня",
  },
  34: {
    "title": "Квартира в старих антибілах",
    "description": "Характерна квартира в центрі В 'єй-Антіба з декором, що поєднує в собі шарм, автентичність і модернізм.",
    "picture": "https://a0.muscache.com/im/pictures/68486179/af61629b_original.jpg?im_w=960",
    "price": "84260 місяць",
    "stars": "5",
    "country": "Франція",
    "nights": "30",
    "date": "1 березня",
  },
  35: {
    "title": "Студія з видом на набережну",
    "description": "Ви оціните його ідеальне розташування та терасу з виходом на південь, комфорт зручностей, гостинність.",
    "picture": "https://a0.muscache.com/im/pictures/2438e632-ac1d-4061-a853-2a5ce5b6fb55.jpg?im_w=960",
    "price": "51507 місяць",
    "stars": "5",
    "country": "Франція",
    "nights": "30",
    "date": "1 березня",
  },
  36: {
    "title": "Дивовижні види на місто",
    "description": "Пляж Оук-стріт, Мічиган-авеню та Голд-Кост знаходяться неподалік, наші Касас мають гарний зв'язок із Чикаго.",
    "picture": "https://a0.muscache.com/im/pictures/prohost-api/Hosting-44126327/original/e2981f8a-1208-438b-8f00-1849eed6f221.jpeg?im_w=960",
    "price": "151630 місяць",
    "stars": "5",
    "country": "США",
    "nights": "30",
    "date": "1 березня",
  },
  37: {
    "title": "Затишний зруб",
    "description": "Він ідеально підходить для тих, хто бажає жити в затишному місці, де в середньому на 20-25 градусів прохолодніше, ніж Сент-Джордж!",
    "picture": "https://a0.muscache.com/im/pictures/999e90e7-e741-41f3-b6c8-87361adc4893.jpg?im_w=960",
    "price": "78288 місяць",
    "stars": "5",
    "country": "США",
    "nights": "30",
    "date": "1 березня",
  },
  38: {
    "title": "Студія Портленду",
    "description": "Наша студія має  окремий вхід, щоб ви могли приїжджати й виходити, коли забажаєте, з усіма необхідними домашніми зручностями.",
    "picture": "https://a0.muscache.com/im/pictures/27882282/1959afbf_original.jpg?im_w=960",
    "price": "77413 місяць",
    "stars": "5",
    "country": "США",
    "nights": "30",
    "date": "1 березня",
  },
  39: {
    "title": "Ponderous Forest",
    "description": "Ласкаво просимо до моєї країни Home Share у Ла-Пайн! Моє помешкання розташоване на акрах соснового лісу Пондероса.",
    "picture": "https://a0.muscache.com/im/pictures/17173788/57ffd760_original.jpg?im_w=960",
    "price": "44089 місяць",
    "stars": "5",
    "country": "США",
    "nights": "30",
    "date": "1 березня",
  },
  40: {
    "title": "Приватний підвал на вулиці",
    "description": "Окрема квартира в підвалі з власною повною ванною кімнатою та кухнею.",
    "picture": "https://a0.muscache.com/im/pictures/19151397-80a4-4595-a77e-c3c916d9959f.jpg?im_w=960",
    "price": "77223 місяць",
    "stars": "5",
    "country": "США",
    "nights": "30",
    "date": "1 березня",
  },
  41: {
    "title": "Romantic Taormina",
    "description": "Квартира, нещодавно відремонтована, доглянута та чиста, район затишний і комфортний, далеко від хаосу центру міста Летоянні. ",
    "picture": "https://a0.muscache.com/im/pictures/44839555/f6a218f0_original.jpg?im_w=960",
    "price": "51583 місяць",
    "stars": "5",
    "country": "Італія",
    "nights": "30",
    "date": "1 березня",
  },
  42: {
    "title": "Квартира в центрі Катанії",
    "description": "Гарна та затишна незалежна квартира-студія, розташована на вулиці Умберто, в центрі Катанії.",
    "picture": "https://a0.muscache.com/im/pictures/9089617/dd20d615_original.jpg?im_w=960",
    "price": "40513 місяць",
    "stars": "5",
    "country": "Італія",
    "nights": "30",
    "date": "1 березня",
  },
  43: {
    "title": "Квартира з видом на море",
    "description": "Яскрава і панорамна двокімнатна квартира в центрі історичного центру Кастельсардо.",
    "picture": "https://a0.muscache.com/im/pictures/3fb4839d-7957-4645-b3d2-2390844ab805.jpg?im_w=960",
    "price": "53827 місяць",
    "stars": "5",
    "country": "Італія",
    "nights": "30",
    "date": "1 березня",
  },44: {
    "title": "Затишна квартира",
    "description": "Наша чудова залежність від саду та панорамних краєвидів може зручно розмістити двох осіб і ідеально підходить для тих, хто хоче відвідати багато прекрасних пляжів.",
    "picture": "https://a0.muscache.com/im/pictures/f4eacaaf-523b-4f77-a578-bedde8972b15.jpg?im_w=960",
    "price": "57213 місяць",
    "stars": "5",
    "country": "Італія",
    "nights": "30",
    "date": "1 березня",
  },45: {
    "title": "Номер поблизу Торвергата",
    "description": "Хороша кімната поблизу університету та Поліклініко Торвергати, чиста та комфортна.",
    "picture": "https://a0.muscache.com/im/pictures/fee51904-56b4-481c-8612-a740852cbd7f.jpg?im_w=960",
    "price": "44279 місяць",
    "stars": "5",
    "country": "Італія",
    "nights": "30",
    "date": "1 березня",
  },46: {
    "title": "Романтична квартира",
    "description": "Розташований на шостому поверсі будинку з ліфтом, тихий і повітряний.",
    "picture": "https://a0.muscache.com/im/pictures/164b55bd-6817-4913-a4a9-d5df906b3ad4.jpg?im_w=960",
    "price": "49529 місяць",
    "stars": "5",
    "country": "Італія",
    "nights": "30",
    "date": "1 березня",
  },
  47: {
    "title": "Будинок Росіти",
    "description": "Квартира з трьома спальнями ідеально підходить для відпочинку на пляжах Роти та її незрівнянних пейзажів та природних просторів. ",
    "picture": "https://a0.muscache.com/im/pictures/676a1c34-262c-40f4-9c55-550f7cfa255d.jpg?im_w=960",
    "price": "62006 місяць",
    "stars": "5",
    "country": "Іспанія",
    "nights": "30",
    "date": "1 березня",
  },
  48: {
    "title": "Красива студія",
    "description": "Красивий лофт, дуже яскравий, зручний, зі спальнею, вітальнею, кухнею (повністю обладнаною)",
    "picture": "https://a0.muscache.com/im/pictures/bdefa257-5589-48e5-8944-c35fe2fc0c13.jpg?im_w=960",
    "price": "65506 місяць",
    "stars": "5",
    "country": "Іспанія",
    "nights": "30",
    "date": "1 березня",
  },
  49: {
    "title": "Квартира неподалік від пляжу",
    "description": "Квартира біля пляжу. Дуже тихий район. Тут є всі зручності поблизу (супермаркети, кафе, розваги).",
    "picture": "https://a0.muscache.com/im/pictures/aa4b7bf3-0feb-4e8b-817f-987ad962f600.jpg?im_w=960",
    "price": "61816 місяць",
    "stars": "5",
    "country": "Іспанія",
    "nights": "30",
    "date": "1 березня",
  },
  50: {
    "title": "Квартира в Вівейро Місто",
    "description": "Цікаві місця: повністю обладнана квартира з гаражем, з неймовірним видом на лимани, поблизу пляжів!!! ",
    "picture": "https://a0.muscache.com/im/pictures/f2ed4f3f-bd43-4f76-94c5-b91bb5ea5ac4.jpg?im_w=960",
    "price": "81293 місяць",
    "stars": "5",
    "country": "Іспанія",
    "nights": "30",
    "date": "1 березня",
  },
  51: {
    "title": "Вражаючий вид на море",
    "description": "Чудова квартира, щойно переобладнана, з вражаючим видом на море, у приватній спільноті з басейном та паркінгом",
    "picture": "https://a0.muscache.com/im/pictures/bc502ed2-e90f-47ab-962c-789ff0dff5f8.jpg?im_w=1200",
    "price": "122225 місяць",
    "stars": "5",
    "country": "Іспанія",
    "nights": "30",
    "date": "1 березня",
  },
  52: {
    "title": "Квартира неподалік від пляжу",
    "description": "Квартира біля пляжу. Тут є всі зручності поблизу (супермаркети, кафе, розваги). Відмінний вид на море та гори.",
    "picture": "https://a0.muscache.com/im/pictures/aa4b7bf3-0feb-4e8b-817f-987ad962f600.jpg?im_w=960",
    "price": "61816 місяць",
    "stars": "5",
    "country": "Іспанія",
    "nights": "30",
    "date": "1 березня",
  },
}